{
    "name": "Letters",
    "summary": "Manage letter",
    "author": "Pinto",
    "website": "https://github.com/quantum-pinto/odoo-modules",
    "version": "17.0.1.0.0",
    "license": "Other proprietary",
    "category": "Uncategorized",
    "depends": [
        "base",
        "mail",
        "pipeline",
        "email_template_qweb",
    ],
    "data": [
        "security/ir_module_category.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        "reports/ir_actions_report.xml",
        "views/letter_menus.xml",
        "views/letter_type_stage.xml",
        "views/letter_type.xml",
        "views/letter_letter.xml",
        "views/letter_dashboard.xml",
        "wizard/letter_mail_wizard.xml",
        "views/letter_inbound.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "letter/static/src/fonts/univers-lt-std-webfont/style.css",
            "letter/static/src/scss/report.scss",
        ],
        "web.report_assets_common": [
            "letter/static/src/fonts/univers-lt-std-webfont/style.css",
            "letter/static/src/scss/report.scss",
        ],
    },
    "application": True,
}
